<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Domain\XovoeJ.Entities\XovoeJ.Entities.csproj" />
		<ProjectReference Include="..\..\Infrastructure\XovoeJ.Persistence.PostgreSql\XovoeJ.Persistence.PostgreSql.csproj" />
		<ProjectReference Include="..\..\Shared\XovoeJ.Abstractions\XovoeJ.Abstractions.csproj" />
		<ProjectReference Include="..\..\Shared\XovoeJ.Contracts\XovoeJ.Contracts.csproj" />
		<ProjectReference Include="..\..\Shared\XovoeJ.Enum\XovoeJ.Enum.csproj" />
		<ProjectReference Include="..\..\Shared\XovoeJ.EventBus\XovoeJ.EventBus.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.4" />
	</ItemGroup>
</Project>
